### ISSUE TITLE
 Migrar a Python 3

### ISSUE THREAD

**Issue by gabelula** [ladiaria/utopia-crm#2]
2.7 is deprecated and we need to move sooner to Python 3.

Some resources to help with the migration: 

- https://docs.python.org/3/howto/pyporting.html
- https://stxnext.com/blog/2019/04/16/python-3-migration-guide/
- https://portingguide.readthedocs.io/en/latest/

**Comment by virusereturns** [comment]
For now the priority should be migrating to python 3.7 which is the latest python3 that supports django 1.11.

All the requirements seem to install OK on a 3.7 virtual environment.

**Comment by anibalpacheco** [comment]
done some months ago
