### ISSUE TITLE
js error in "home" after a new installation

### ISSUE THREAD

**Issue by anibalpacheco** [ladiaria/utopia-crm#45]
screenshot attached
![Screenshot from 2021-03-09 01-04-13](https://user-images.githubusercontent.com/89636/110424265-47e10d80-8081-11eb-8ac4-d66cd281535c.png)

**Comment by virusereturns** [comment]
This has been fixed by importing jquery and jquery-ui when it's supposed to be imported and changed all the instances of extra_head to extra_js when extra javascript is needed to be run.
